apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-chatbot.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "todo-chatbot.backend.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    {{- if and (eq .Values.backend.service.type "NodePort") .Values.backend.service.nodePort }}
    nodePort: {{ .Values.backend.service.nodePort }}
    {{- end }}
  sessionAffinity: None
